GET http://localhost:3000/conversations
Authorization: Bearer 1058824|yF9Vhc5nJSz0Fjw1hCgoYbsk9ITggbB6SENcDx9G
###

POST http://localhost:3000/conversations
Content-Type: application/json
{
    "name":"amil ali sahil"
}
###
GET http://localhost:3000/messages

###
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJSYW5hIiwiX2lkIjoiNjUxNmZjMmFmMDhkNjdhZGI3YTY0MTk1IiwiY3JlYXRlZEF0IjoiMjAyMy0wOS0yOVQxNjozMjo0Mi41NjNaIn0sImlhdCI6MTY5NjAwNTE2Mn0.hZdnKxFH2QMs0LoyNSS8EgT5Q1CRrQbTs7zebdRQKOs

{
    "text":"hello",
    "title":"Friend",
    "conversationId":"6506f46365d3808696c6ef0a"
}
###
POST http://localhost:3000/users

###
POST http://localhost:3000/users/verify-token
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJSYW5hIiwiX2lkIjoiNjUxNmZjMmFmMDhkNjdhZGI3YTY0MTk1IiwiY3JlYXRlZEF0IjoiMjAyMy0wOS0yOVQxNjozMjo0Mi41NjNaIn0sImlhdCI6MTY5NjAwNTE2Mn0.hZdnKxFH2QMs0LoyNSS8EgT5Q1CRrQbTs7zebdRQKOs

###
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJSYW5hIiwiX2lkIjoiNjUxNmZjMmFmMDhkNjdhZGI3YTY0MTk1IiwiY3JlYXRlZEF0IjoiMjAyMy0wOS0yOVQxNjozMjo0Mi41NjNaIn0sImlhdCI6MTY5NjAwNTE2Mn0.hZdnKxFH2QMs0LoyNSS8EgT5Q1CRrQbTs7zebdRQKOs

{
    "title":"Friend",
    "text":"hello dear",
}